# Generated by Django 5.0.6 on 2024-07-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_delete_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Adress',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='College',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='RollNo',
        ),
    ]
