# Generated by Django 5.1.1 on 2024-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_otp_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_verification',
            field=models.IntegerField(max_length=999999, null=True, unique=True),
        ),
    ]
