# Generated by Django 5.1 on 2024-09-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='Skills',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='internship',
            name='Status',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='user_id',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='internship',
            name='username',
            field=models.CharField(default='null', max_length=400),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Description',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Duration',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Mentor',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Title',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
