# Generated by Django 5.0.6 on 2024-07-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('College', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=10)),
                ('RollNo', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
    ]
