# Generated by Django 5.0.6 on 2024-07-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adddress', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
