# Generated by Django 5.1 on 2024-09-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addskills',
            field=models.CharField(default='null', max_length=400),
        ),
        migrations.AddField(
            model_name='student',
            name='i_id',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='idCard',
            field=models.FileField(default='null', upload_to='id/'),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(default='null', max_length=400),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='adddress',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(default='null', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
